"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BOT_THRESHOLD = exports.CHANCE_FOR_BOT = exports.NUMBER_OF_LAST_OPPONENTS_TO_EXCLUDE = exports.MATCH_ELO_DIFF = exports.DEFAULT_ELO = exports.DUEL_DURATION = exports.ELO_COEFFICIENT = void 0;
const utils_1 = require("../../utils");
exports.ELO_COEFFICIENT = 50;
exports.DUEL_DURATION = 180;
exports.DEFAULT_ELO = 1200;
exports.MATCH_ELO_DIFF = 400;
exports.NUMBER_OF_LAST_OPPONENTS_TO_EXCLUDE = 5;
exports.CHANCE_FOR_BOT = 0.3;
exports.BOT_THRESHOLD = new utils_1.MinMax(0.4, 0.6);
