#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
add_clues_openai.py

Reads the JSON created by the generator, iterates through each crossword and each word,
requests a Polish clue from OpenAI, and writes the updated JSON back to disk.

Usage:
  python add_clues_openai.py crosswords.json --model gpt-4o-mini --rate-limit 30

Environment:
  - OPENAI_API_KEY must be set.
Notes:
  - Idempotent: will not re-generate a clue if the same word already has a clue in the JSON.
  - Basic backoff on API errors.
"""
import argparse
import json
import os
import time
from typing import Dict, Any
from dotenv import load_dotenv

# If you use the official OpenAI SDK >= 1.0
try:
    from openai import OpenAI
except Exception:
    OpenAI = None

BASIC_PROMPT_PL = (
    " \"{word}\". "
)

import json
import time
from typing import Dict, List

def _build_batch_messages(words: List[str]) -> List[Dict[str, str]]:
    # Zwięzłe opisy po 1 na słowo, zwracamy WYŁĄCZNIE JSON { "SŁOWO": "opis" }
    system = (
        "Jesteś twórcą krótkich haseł krzyżówkowych z przymrużeniem oka."
        "Dla każdego słowa wymyśl opis w stylu krzyżówki z przymrużeniem oka"
        "Zwróć WYŁĄCZNIE JSON obiekt mapujący słowo na opis."
    )
    user = (
        "Słowa do opisania z (po jednym opisie na słowo):\n"
        + "\n".join(f"- {w}" for w in words)
        + "\n\nZwróć TYLKO JSON obiekt {\"SŁOWO\":\"opis\"} dla wszystkich słów."
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]

def _request_clues_batch(client, model: str, words: List[str], max_retries: int = 3, delay: float = 2.0) -> Dict[str, str]:
    """
    Jedno wywołanie API, JSON mode. Zwraca mapę {słowo: opis} tylko dla słów z 'words'.
    """
    messages = _build_batch_messages(words)
    for attempt in range(max_retries):
        try:
            resp = client.chat.completions.create(
                model=model,
                messages=messages,
                response_format={"type": "json_object"},
            )
            content = resp.choices[0].message.content or "{}"
            parsed = json.loads(content)

            # Normalizacja: bierzemy tylko klucze odpowiadające wejściowym słowom (case-insensitive OK)
            out = {}
            lower_map = {w.lower(): w for w in words}
            for k, v in parsed.items():
                if not isinstance(k, str) or not isinstance(v, str):
                    continue
                key = k.lower()
                if key in lower_map:
                    out[lower_map[key]] = v.strip()
            return out
        except Exception:
            if attempt == max_retries - 1:
                raise
            time.sleep(delay * (2 ** attempt))
    return {}


def get_client():
    load_dotenv()
    if OpenAI is None:
        raise RuntimeError("OpenAI SDK not available. Install with: pip install openai>=1.0.0")
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("Set OPENAI_API_KEY in environment.")
    return OpenAI(api_key=api_key)

def generate_clue(client, word: str, model: str) -> str:
    # Uses Chat Completions with a single user message prompt in Polish
    msg = BASIC_PROMPT_PL.format(word=word)
    resp = client.chat.completions.create(
        model=model,
        messages=[{"role":"user","content": msg}],
    )
    return resp.choices[0].message.content.strip()

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_path", help="Path to crosswords.json generated by the generator")
    ap.add_argument("--model", default="gpt-5", help="OpenAI model name")
    args = ap.parse_args()

    with open(args.json_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    client = get_client()

    # Build quick lookup to avoid duplicates
    for cw in data.get("crosswords", []):
        # Create a dict (word -> clue) for already present clues
        existing: Dict[str, str] = {
            c["word"].upper(): c["description_pl"]
            for c in cw.get("clues", [])
            if "word" in c and "description_pl" in c
        }

        words = [w["word"].upper() for w in cw.get("words", [])]
        missing_words = [w for w in words if w not in existing]

        if missing_words:
            # 🟢 jeden request na wszystkie brakujące słowa
            batch_map = _request_clues_batch(client, args.model, missing_words)

            to_append = []
            for w in missing_words:
                clue = batch_map.get(w)
                if clue:
                    print(f"Generated clue for {w}: {clue}")
                    to_append.append({"word": w, "description_pl": clue})

            if to_append:
                cw.setdefault("clues", []).extend(to_append)



    # Write back
    with open(args.json_path, "w", encoding="utf-8") as out:
        json.dump(data, out, ensure_ascii=False, indent=2)
    print(f"Updated clues and saved to {args.json_path}")

if __name__ == "__main__":
    main()
