#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
upload_to_mongo.py

Reads crosswords JSON and uploads to MongoDB.
Defaults derived from the original script:
- CONNECTION_STRING = "localhost"
- DB name: "test"
- Collection: "possible_crosswords_v2"

You can override via env vars:
  MONGO_URI, MONGO_DB, MONGO_COLLECTION
  DROP_COLLECTION=true|false   (default: true)

Each crossword is inserted as one document:
{
  crossword_id: <int>,
  word_list: [{word, row, col, direction}],   # direction is 'H' or 'V'
  letter_grid: [[str|null]],
  clues: [{word, description}]
}
"""
import argparse
import json
import os
from typing import Any, Dict, List

from pymongo import MongoClient

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_path", help="Path to JSON generated by crossword generator / enriched by add_clues_openai.py")
    args = ap.parse_args()

    uri = os.environ.get("MONGO_URI", "localhost")
    db_name = os.environ.get("MONGO_DB", "test")
    coll_name = os.environ.get("MONGO_COLLECTION", "possible_crosswords_v3")
    drop = os.environ.get("DROP_COLLECTION", "true").lower() == "true"

    client = MongoClient(uri)
    db = client[db_name]
    coll = db[coll_name]
    if drop:
        coll.drop()

    with open(args.json_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    crosswords = data.get("crosswords", [])
    docs: List[Dict[str, Any]] = []
    for cw in crosswords:
        doc = {
            "crossword_id": cw.get("id"),
            "word_list": cw.get("words", []),
            "letter_grid": cw.get("letter_grid", []),
            "clues": cw.get("clues", []),
        }
        docs.append(doc)

    if docs:
        coll.insert_many(docs)
    print(f"Uploaded {len(docs)} crosswords to {db_name}.{coll_name} (URI={uri})")

if __name__ == "__main__":
    main()
